### ISSUE TITLE
Appdata is missing screenshots

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/de.rwth_aachen.ient.RDPlot#1]
I couldn't find any elsewhere on the web either.

**Comment by nedrichards** [comment]
It's also missing categories (which you need to add to the desktop file, fwiw) your choice of categories must come from https://standards.freedesktop.org/menu-spec/latest/apa.html and https://standards.freedesktop.org/menu-spec/latest/apas02.html

**Comment by nolyn** [comment]
should be fixed now
